project:
  type: website
  output-dir: C:/Users/melser/Documents/GitHub/FCOR-599-Workshops

website:
  title: "FCOR 599: Workshop Artifacts"
  sidebar:
    logo: images/MGEM_logo.png
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: Landing_Page/index.qmd
      - section: "Cartography"
        href: Cartography/cartography.qmd
        contents:
          - Cartography/art_of_maps.qmd
          - Cartography/arcgis_pro_demo.qmd
      - section: "Interactive Maps"
        href: Interactive_Maps/interactive_maps.qmd
        contents: 
          - Interactive_Maps/leaflet.qmd
          
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

