project:
  type: website
  output-dir: C:/Users/melser/Documents/GitHub/FCOR-599-Workshops

website:
  title: "FCOR 599: Workshop Artifacts"
  sidebar:
    logo: images/MGEM_logo.png
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "E-portfolio"
        href: E-Portfolio/eportfolio.qmd
      - section: "Interactive Maps"
        href: Interactive_Maps/interactive_maps.qmd
        contents: 
          - Interactive_Maps/leaflet.qmd
      - text: "Coding Crossover"
        href: CodingCrossover/codingcrossover.qmd
      - section: "Cartography"
        href: Cartography/cartography.qmd
        contents:
          - Cartography/art_of_maps.qmd
          - Cartography/arcgis_pro_demo.qmd
      - text: "Shiny"
        href: Shiny/shiny.qmd
      - text: "Report-Ready Figures in ggplot"
        href: ggplot/MEGEM_ggplot/ggplot.qmd
      - text: "Github Intro"
        href: GitHub_workshop/GitHub_workshop/Intro_to_GitHub.qmd
      
      
          
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

