project:
  type: website
  output-dir: C:/Users/melser/Documents/GitHub/FCOR-599-Workshops

website:
  title: "FCOR 599: Workshop Artifacts"
  sidebar:
    logo: images/MGEM_logo.png
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Cartography"
        href: cartography.qmd
        contents:
          - art_of_maps.qmd
          - arcgis_pro_demo.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

